### ISSUE TITLE
new installation

### ISSUE THREAD

**Issue by wifi75** [OpenSprinkler/OpenSprinkler-Weather#110]
hello I don't know but after new installtion not work:

why?

```
 /home/pi/ospiLCD.py
Traceback (most recent call last):
  File "/home/pi/ospiLCD.py", line 50, in <module>
    ja = get_data(api_url)
  File "/home/pi/ospiLCD.py", line 46, in get_data
    variables = json.loads(data, object_hook=lambda d: namedtuple('X', d.keys())(*d.values()))
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/pi/ospiLCD.py", line 46, in <lambda>
    variables = json.loads(data, object_hook=lambda d: namedtuple('X', d.keys())(*d.values()))
  File "/usr/lib/python2.7/collections.py", line 354, in namedtuple
    'keyword: %r' % name)
ValueError: Type names and field names cannot be a keyword: 'pass'

```

**Comment by wifi75** [comment]
sorry...
